### ISSUE TITLE
Questions regarding Dockerfile

### ISSUE THREAD

**Issue by php-coder** [spring-guides/gs-spring-boot-kubernetes#1]
Hi and thank you for the guide!

There is one non-clear moment to me that I'd like to ask. In most of the guides that I've seen, people use `java -jar` approach while in this guide we unpack JAR's and copy its content.

I suspect that there is a reason why we follow this path. Is it some kind of optimization? It seems that it will be faster because we don't need to unpack JAR in a runtime. Is this that reason? How much the win will be here?

Another theory is that this approach gives us benefits regarding a caching of the image layers. Is that true?

Thanks!

**Comment by php-coder** [comment]
Also I'm wondering what's the purpose of

> ARG DEPENDENCY=target/dependency

?

**Comment by php-coder** [comment]
I see that this is indeed layer-optimization that is explained at https://spring.io/guides/topicals/spring-boot-docker/ Perhaps, we can add a link to this topic.

**Comment by dsyer** [comment]
It's both faster to start up and more efficient layering. There is already a link to that guide in this one. If you want to put another one in a more specific place, you could send a PR. The "DEPENDENCY" build arg is just a way of reducing repetition in the Dockerfile. It's a matter of taste really.
